### ISSUE TITLE
[Feature request] Skip existing files

### ISSUE THREAD

**Issue by jtjb07** [crptmem/boostydownloader#1]
Hi, 

Thanks for writing this, it's working great. One small request - would it be possible to add an option to skip over files that have already been downloaded on a rerun of the script, instead of redownloading and overwriting them?

I have a few larger accounts with a ton of VODs that will probably take a few days to download. My connection drops out every once in a while, causing the script to break, meaning I'm unlikely to ever finish downloading them

Thanks mate

**Comment by crptmem** [comment]
Done by [e90c098](https://github.com/crptmem/boostydownloader/commit/e90c098bbe23dffd4c2efaa71130e2829d0d5c4e), thank you! Please tell me if it works not as expected.
