### ISSUE TITLE
[Feature request] Download videos

### ISSUE THREAD

**Issue by izzqz** [crptmem/boostydownloader#3]
Im trying to download videos using yt-dlp with cookies file but it doesn't work for me. This tool is gonna be huge W if its able to bump all boosty content with videos

**Comment by crptmem** [comment]
Implemented by [c5976cc](https://github.com/crptmem/boostydownloader/commit/c5976cc03c19e0edac65244ae6812915e411efd0), now `boostydownloader` is able to download videos uploaded to Boosty, but not YouTube videos.
