### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by biggestsonicfan** [crptmem/boostydownloader#4]
```
thread 'main' panicked at C:\Users\XXXXX\.cargo\registry\src\index.crates.io-6f17d22bba15001f\boostydownload-0.2.2\src\utils\mod.rs:14:95:
```

**Comment by ChrisIsEditing** [comment]
Getitng this too

**Comment by ChrisIsEditing** [comment]
Getting this error too

`thread 'main' panicked at /home/XXX/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boostydownload-0.2.2/src/utils/mod.rs:14:95: called `Option::unwrap()` on a `None` value`

**Comment by biggestsonicfan** [comment]
Fixed!
